"""empty message

Revision ID: 3d9311087be6
Revises: 
Create Date: 2022-02-06 13:53:29.813694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d9311087be6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("profiles", "is_active")
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.add_column(
        "profiles",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.alter_column("profiles", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
